# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/aldric-l/Documents/C++ Dev/DDPG-Oligopolies-Simulator"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/aldric-l/Documents/C++ Dev/DDPG-Oligopolies-Simulator"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/aldric-l/Documents/C++ Dev/DDPG-Oligopolies-Simulator/CMakeFiles" "/Users/aldric-l/Documents/C++ Dev/DDPG-Oligopolies-Simulator//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/aldric-l/Documents/C++ Dev/DDPG-Oligopolies-Simulator/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DDPG-Oligopolies-Simulator

# Build rule for target.
DDPG-Oligopolies-Simulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DDPG-Oligopolies-Simulator
.PHONY : DDPG-Oligopolies-Simulator

# fast build rule for target.
DDPG-Oligopolies-Simulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DDPG-Oligopolies-Simulator.dir/build.make CMakeFiles/DDPG-Oligopolies-Simulator.dir/build
.PHONY : DDPG-Oligopolies-Simulator/fast

#=============================================================================
# Target rules for targets named AKML

# Build rule for target.
AKML: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AKML
.PHONY : AKML

# fast build rule for target.
AKML/fast:
	$(MAKE) $(MAKESILENT) -f Simulator/AKML-lib/CMakeFiles/AKML.dir/build.make Simulator/AKML-lib/CMakeFiles/AKML.dir/build
.PHONY : AKML/fast

#=============================================================================
# Target rules for targets named AKML_AgentBasedUtilities

# Build rule for target.
AKML_AgentBasedUtilities: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AKML_AgentBasedUtilities
.PHONY : AKML_AgentBasedUtilities

# fast build rule for target.
AKML_AgentBasedUtilities/fast:
	$(MAKE) $(MAKESILENT) -f Simulator/AKML-lib/AgentBasedUtilities/CMakeFiles/AKML_AgentBasedUtilities.dir/build.make Simulator/AKML-lib/AgentBasedUtilities/CMakeFiles/AKML_AgentBasedUtilities.dir/build
.PHONY : AKML_AgentBasedUtilities/fast

Simulator/LearningAgent.o: Simulator/LearningAgent.cpp.o
.PHONY : Simulator/LearningAgent.o

# target to build an object file
Simulator/LearningAgent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DDPG-Oligopolies-Simulator.dir/build.make CMakeFiles/DDPG-Oligopolies-Simulator.dir/Simulator/LearningAgent.cpp.o
.PHONY : Simulator/LearningAgent.cpp.o

Simulator/LearningAgent.i: Simulator/LearningAgent.cpp.i
.PHONY : Simulator/LearningAgent.i

# target to preprocess a source file
Simulator/LearningAgent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DDPG-Oligopolies-Simulator.dir/build.make CMakeFiles/DDPG-Oligopolies-Simulator.dir/Simulator/LearningAgent.cpp.i
.PHONY : Simulator/LearningAgent.cpp.i

Simulator/LearningAgent.s: Simulator/LearningAgent.cpp.s
.PHONY : Simulator/LearningAgent.s

# target to generate assembly for a file
Simulator/LearningAgent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DDPG-Oligopolies-Simulator.dir/build.make CMakeFiles/DDPG-Oligopolies-Simulator.dir/Simulator/LearningAgent.cpp.s
.PHONY : Simulator/LearningAgent.cpp.s

Simulator/SimulationManager.o: Simulator/SimulationManager.cpp.o
.PHONY : Simulator/SimulationManager.o

# target to build an object file
Simulator/SimulationManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DDPG-Oligopolies-Simulator.dir/build.make CMakeFiles/DDPG-Oligopolies-Simulator.dir/Simulator/SimulationManager.cpp.o
.PHONY : Simulator/SimulationManager.cpp.o

Simulator/SimulationManager.i: Simulator/SimulationManager.cpp.i
.PHONY : Simulator/SimulationManager.i

# target to preprocess a source file
Simulator/SimulationManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DDPG-Oligopolies-Simulator.dir/build.make CMakeFiles/DDPG-Oligopolies-Simulator.dir/Simulator/SimulationManager.cpp.i
.PHONY : Simulator/SimulationManager.cpp.i

Simulator/SimulationManager.s: Simulator/SimulationManager.cpp.s
.PHONY : Simulator/SimulationManager.s

# target to generate assembly for a file
Simulator/SimulationManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DDPG-Oligopolies-Simulator.dir/build.make CMakeFiles/DDPG-Oligopolies-Simulator.dir/Simulator/SimulationManager.cpp.s
.PHONY : Simulator/SimulationManager.cpp.s

Simulator/main.o: Simulator/main.cpp.o
.PHONY : Simulator/main.o

# target to build an object file
Simulator/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DDPG-Oligopolies-Simulator.dir/build.make CMakeFiles/DDPG-Oligopolies-Simulator.dir/Simulator/main.cpp.o
.PHONY : Simulator/main.cpp.o

Simulator/main.i: Simulator/main.cpp.i
.PHONY : Simulator/main.i

# target to preprocess a source file
Simulator/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DDPG-Oligopolies-Simulator.dir/build.make CMakeFiles/DDPG-Oligopolies-Simulator.dir/Simulator/main.cpp.i
.PHONY : Simulator/main.cpp.i

Simulator/main.s: Simulator/main.cpp.s
.PHONY : Simulator/main.s

# target to generate assembly for a file
Simulator/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DDPG-Oligopolies-Simulator.dir/build.make CMakeFiles/DDPG-Oligopolies-Simulator.dir/Simulator/main.cpp.s
.PHONY : Simulator/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AKML"
	@echo "... AKML_AgentBasedUtilities"
	@echo "... DDPG-Oligopolies-Simulator"
	@echo "... Simulator/LearningAgent.o"
	@echo "... Simulator/LearningAgent.i"
	@echo "... Simulator/LearningAgent.s"
	@echo "... Simulator/SimulationManager.o"
	@echo "... Simulator/SimulationManager.i"
	@echo "... Simulator/SimulationManager.s"
	@echo "... Simulator/main.o"
	@echo "... Simulator/main.i"
	@echo "... Simulator/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

